# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ScrollView+Autolayout' do

pod 'Masonry', '~> 0.6.4'
pod 'SDWebImage', '~> 3.7.5'
pod 'MJExtension', '~> 3.0.10'

end

target 'ScrollView+AutolayoutTests' do

end

target 'ScrollView+AutolayoutUITests' do

end

